# Generated by Django 3.0.8 on 2020-08-06 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=20)),
                ('blog_img', models.ImageField(upload_to='pics')),
                ('blog_desc', models.CharField(blank=True, max_length=200)),
                ('blog_author', models.CharField(blank=True, max_length=20)),
                ('html_enabled', models.BooleanField(default=False)),
                ('blog_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='Carosels')),
                ('carousel_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=500)),
                ('message_given', models.CharField(max_length=500)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('html_enabled', models.BooleanField(default=False)),
                ('course_prequesites_details', models.TextField()),
                ('content_details', models.TextField()),
                ('course_img', models.ImageField(upload_to='pics')),
                ('overview', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('no_of_weeks', models.CharField(max_length=50)),
                ('course_level', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('popular', models.BooleanField(default=False)),
                ('stike_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=1000)),
                ('week_id', models.IntegerField()),
                ('attempt', models.BooleanField(default=False)),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=30)),
                ('development', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('mentor_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('subtitle', models.TextField()),
                ('facebook_link', models.CharField(max_length=50)),
                ('linkedin_link', models.CharField(max_length=40)),
                ('instagram_link', models.CharField(max_length=30)),
                ('image_team', models.ImageField(upload_to='OurTeam')),
            ],
        ),
        migrations.CreateModel(
            name='PsychoQues',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField()),
                ('choice_4', models.TextField()),
                ('choice_5', models.TextField(blank=True)),
                ('correct_answer', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_no', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('test_available', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField()),
                ('choice_4', models.TextField()),
                ('correct_answer', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Weeks')),
            ],
        ),
        migrations.CreateModel(
            name='PsychoTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('choices', models.TextField(null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profileEditQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(max_length=1000)),
                ('answer2', models.TextField(max_length=1000)),
                ('answer3', models.TextField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to='profileImages')),
                ('user_contact_number', models.CharField(max_length=12)),
                ('user_college_name', models.CharField(max_length=50)),
                ('user_branch_name', models.CharField(max_length=30)),
                ('onces', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollement',
            fields=[
                ('registration_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('date_of_enrollement', models.DateField(auto_now_add=True)),
                ('date_of_completion', models.DateField()),
                ('token_id', models.CharField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Courses')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='mentor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Mentor'),
        ),
    ]
