# Generated by Django 3.0.8 on 2020-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200911_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='link',
            field=models.TextField(default='<div id="extdiv">\n<div  class="embed-responsive embed-responsive-16by9 ">\n<iframe style="max-height: 750px;  width=40%; "  class="embed-responsive-item"  src="https://www.youtube.com/embed/Lcxm0jCgQs0" frameborder="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>\n</div>\n<h3 style="margin-top:20px;">Conversion of NFA to Equivalent DFA</h3>\n</div>\n<style>\n#extdiv{\nmargin-left:20%;\n}\n@media screen and (max-width: 700px) {\n  #extdiv {\npadding: 0;\nmargin: 0;\n    width: 100%;\n    height: auto;\n\n  }\n}\n</style> '),
        ),
    ]
