# Generated by Django 3.0.8 on 2020-09-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrole',
            old_name='responsibilities',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='prospects',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='working_hrs',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='syllabus',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
